# fly.toml app configuration file generated for lumeo on 2025-05-09T00:43:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lumeo"
primary_region = "dfw"

[build]
  [build.args]
    NODE_VERSION = "18.19.1"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "3001"
  NODE_ENV = "production"



[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]

  [[services.ports]]
    port = 8080
    handlers = ["http"]

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"
    protocol = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
