app = "lumeo"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"
  NODE_ENV = "production"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443

  [http_service.concurrency]
    type = "connections"
    hard_limit = 550
    soft_limit = 500

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/api/health"
    protocol = "http"