app = "lumeo"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"
  NODE_ENV = "production"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 5000
  force_https = true

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"
    protocol = "http"